### ISSUE TITLE
Project build fails

### ISSUE THREAD

**Issue by jeremyrempel** [davideast/firebase-react-native-sample#31]
=== BUILD TARGET RCTLinking OF PROJECT RCTLinking WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET RCTVibration OF PROJECT RCTVibration WITH CONFIGURATION Debug ===

Check dependencies

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/jrempel/WebstormProjects/firebase-react-native-sample/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/FirebaseReactNativeSample.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
(node:32368) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/FirebaseReactNativeSample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:588:13)
    at Object.execFileSync (child_process.js:608:13)
    at _runIOS (/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
    at Promise (/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5)
    at tryCallTwo (/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/jrempel/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/cliEntry.js:95:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:117:7)

**Comment by harrigee** [comment]
i restarted my mac and built it directly via xcode. that solved my problem.

**Comment by haohoangtran** [comment]
![screen shot 2017-09-05 at 7 50 59 pm](https://user-images.githubusercontent.com/16833193/30061944-9e576c4a-9273-11e7-8c8c-e08d5f5955fa.png)
work for me!

**Comment by ahmedamasha** [comment]
The following build commands failed:
	CompileC /Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/FirebaseReactNativeSample.app
No devices are booted.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
(node:3420) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/FirebaseReactNativeSample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:591:13)
    at Object.execFileSync (child_process.js:611:13)
    at _runIOS (/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
    at Promise (/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5)
    at tryCallTwo (/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/ahmedamasha/WebstormProjects/firebase-react-native-sample/node_modules/react-native/local-cli/cliEntry.js:95:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:117:7)

**Comment by ahmedamasha** [comment]
same with me

**Comment by haohoangtran** [comment]
@ahmedibrahimamasha:

here is solution:

build example with xcode, issue like this
![image](https://user-images.githubusercontent.com/16833193/30308809-e9755d98-97b1-11e7-87f0-93f088355dca.png)
click issue and edit 2 occurences of calls to SecRandomCopyBytes like this:

![image](https://user-images.githubusercontent.com/16833193/30061944-9e576c4a-9273-11e7-8c8c-e08d5f5955fa.png)

**Comment by WoodyPhil** [comment]
@davideast will you update this?
